services:
  - type: web
    name: laravel-abcc
    env: docker
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:...
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://proyectoabcc-laravel-final.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: btldotgudhylexb18sey-mysql.services.clever-cloud.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: btldotgudhylexb18sey
      - key: DB_USERNAME
        value: uver4zyp7czemcjo
      - key: DB_PASSWORD
        value: 3RVgPRApcLX9SlcwepRe
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
